todo_project/fbv_todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.todo_list_view, name='todo_list'),
    path('items/completed', views.todo_completed_list_view, name='show_completed'),
    path('item/<int:id>/', views.todo_detail_view, name='todo_detail'),
    path('item/<int:id>/delete/', views.todo_delete_view, name='todo_delete'),
    path('item/create/', views.todo_create_view, name='todo_create'),
    path('item/<int:id>/update/', views.todo_update_view, name='todo_update'),
    path('item/<int:id>/complete/', views.todo_mark_as_completed_or_incompleted_view, name='todo_complete'),
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fbv_todo.urls')),
]

todo_project/fbv_todo/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class ToDo(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    
    class ToDoPriority(models.TextChoices):
        HIGH_PRIORITY = 'High', _('High Priority')
        LOW_PRIORITY = 'Low', _('Low Priority')
    priority = models.CharField(
        max_length=5, 
        choices=ToDoPriority.choices,
        default=ToDoPriority.HIGH_PRIORITY
        )

    completed = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title

todo_project/fbv_todo/forms.py
from django.forms import ModelForm
from .models import ToDo

class ToDoForm(ModelForm):
    class Meta:
        model = ToDo
        fields = [
            'title',
            'description',
            'priority',
        ]

todo_project/fbv_todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import ToDo
from .forms import ToDoForm


def todo_list_view(request):
    queryset = ToDo.objects.filter(completed=False)
    context ={
    'object_list': queryset,
    }
    template_name = 'fbv_todo/todo_list.html'
    return render(request, template_name, context)

def todo_completed_list_view(request):
    queryset = ToDo.objects.filter(completed=True)
    context ={
    'object_list': queryset,
    'complete': True,
    }
    template_name = 'fbv_todo/todo_list.html'
    return render(request, template_name, context)

def todo_detail_view(request, id):
    queryset = get_object_or_404(ToDo, id=id) 
    context ={
    'object': queryset,
    }
    template_name = 'fbv_todo/todo_detail.html'
    return render(request, template_name, context)

def todo_create_view(request):
    form = ToDoForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Item added successfully, Add another')
        return redirect('todo:todo_create') 
    context ={
    'form': form,
    }
    template_name = 'fbv_todo/todo_create.html'
    return render(request, template_name, context)

def todo_update_view(request, id):
    queryset = get_object_or_404(ToDo, id=id) 
    if request.method == 'POST' and queryset.completed == True:
        queryset.completed = False
        queryset.save()
    form = ToDoForm(request.POST or None, instance=queryset)
    if form.is_valid():
        form.save()
        return redirect('todo:todo_list') 
    context ={
    'object': queryset,
    'form': form,
    }
    template_name = 'fbv_todo/todo_update.html'
    return render(request, template_name, context)


def todo_delete_view(request, id):
    queryset = get_object_or_404(ToDo, id=id)
    if request.method == 'POST':
        queryset.delete()
        return redirect('todo:todo_list') 
    context ={
    'object': queryset,
    }
    template_name = 'fbv_todo/todo_delete.html'
    return render(request, template_name, context)

def todo_mark_as_completed_or_incompleted_view(request, id):
    queryset = get_object_or_404(ToDo, id=id)
    if queryset.completed == False:
        queryset.completed = True
    else:
        queryset.completed = False
    queryset.save()    
    return redirect('todo:todo_list')

todo_project/fbv_todo/templates/fbv_todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To Do App</title>

    <style>
        nav{
            margin:20px 15px;
        }
        a{
            margin:3px;
            padding:3px;
            color:blue
        }
        .dg{
            color:red;
        }
        .d{
            color:green;
        }
        .t{
            color:cyan;
        }
        .i{
            color:skyblue;
        }
       hr{
            margin:20px 5px 5px 5px;
       }
           
       
    </style>
</head>
<body>
<nav><a href="{% url 'todo:todo_list' %}">Home</a></nav>
<h1>BASIC TO DO APP </h1>
    {% block content %}
    {% endblock content %}
<hr>
<footer>
    <p>Copyright &copy;2020, Hopson Gausi. </p>
</footer>
</body>
</html>

todo_project/fbv_todo/templates/fbv_todo/todo_create.html
{% extends 'fbv_todo/base.html' %}

{% block content %}
{% for message in messages %}
<p class="d">{{ message }}</p>
{% endfor %}
    <form action="{% url 'todo:todo_create'%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add"> <a href="{% url 'todo:todo_list' %}">View todo items</a>
    </form>
{% endblock content %}

todo_project/fbv_todo/templates/fbv_todo/todo_delete.html
{% extends 'fbv_todo/base.html' %}

{% block content %}
    <p>Are you sure you want to delete <strong>{{object.title}}</strong>?</p>
    <form action="{% url 'todo:todo_delete' object.id%}" method="post">
        {% csrf_token %}
        <input type="submit" value="yes" class="dg">
            <a href="{% url 'todo:todo_list' %}">no</a>
    </form>
{% endblock content %}

todo_project/fbv_todo/templates/fbv_todo/todo_detail.html
{% extends 'fbv_todo/base.html' %}

{% block content %}
        <h4>[A To Do Item Details]</h4>
        <p>Title: <span class="i"> {{ object.title}} </span> </p>
        <p><strong><em>priority</em></strong>: <strong>{{ object.priority}}</strong> </p>
        <p>Description: <span class="i"> {{ object.description }} </span> </p>
        <a href="{% url 'todo:todo_complete' object.id %}" class="d">mark as completed</a>
        <a href="{% url 'todo:todo_delete' object.id%}" class="dg">delete</a> 
        <a href="{% url 'todo:todo_update' object.id%}">update</a>

{% endblock content %}

todo_project/fbv_todo/templates/fbv_todo/todo_list.html
{% extends 'fbv_todo/base.html' %}
{% load todo_tags %}
{% block content %}
    {% for object in object_list %}
       <p> 
            <strong>{{ forloop.counter}}.</strong> 
            <a href="{% url 'todo:todo_detail' object.id %}">{{ object.title}}</a>
             -----[<strong><em>priority</em></strong>: <strong>{{ object.priority}}</strong>] 

            <a href="{% url 'todo:todo_delete' object.id%}" class="dg">delete</a>
            {% if object.completed %}
                 <a href="{% url 'todo:todo_complete' object.id %} " class="d">mark as incomplete</a>
            {% else %}
                <a href="{% url 'todo:todo_complete' object.id %} " class="d">mark as complete</a>
            {% endif %}
             
        </p>
    {% endfor %}
    <a href="{% url 'todo:todo_create' %}" class="t">[Add a to-do item]</a>
    {% if complete %}
        <a href="{% url 'todo:todo_list' %}" class="t">
            [Not completed({{ object_list|icount}})]
        </a>
    {% else %}
        <a href="{% url 'todo:show_completed' %}" class="t">
            [Completed({{ object_list|ccount}})]
        </a>
    {% endif %}
    
    
{% endblock content %}

todo_project/fbv_todo/templates/fbv_todo/todo_update.html
{% extends 'fbv_todo/base.html' %}

{% block content %}
    <form action="{% url 'todo:todo_update' object.id%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="update"> 
    </form>
{% endblock content %}